#!/usr/bin/env python

import optparse
p = optparse.OptionParser()
p.add_option("--server-hostname", dest="hostname", type="string")
(opts,args) = p.parse_args()

if (type(opts.hostname) == str and opts.hostname.startswith("stage")):
    for path in ["jsapi/include.js"]:
        file_contents = ""
        with open(path, "r") as fp:
            file_contents = fp.read()
        file_contents = file_contents.replace("//myapps.mozillalabs.com","//stage.myapps.mozillalabs.com")
        with open(path, "w+") as fp:
            fp.write(file_contents)
