#!/usr/bin/env python

import optparse
p = optparse.OptionParser()
p.add_option("--server-hostname", dest="hostname", type="string")
(opts,args) = p.parse_args()

replacements = {
    "//myapps.mozillalabs.com": "//stage.myapps.mozillalabs.com",
    "//appstore.mozillalabs.com": "//stage.appstore.mozillalabs.com",
    "8500": "8501"
}

if (type(opts.hostname) == str and opts.hostname.startswith("stage")):
    for path in ["server.py", "no_user_index.html"]:
        file_contents = ""
        with open(path, "r") as fp:
            file_contents = fp.read()
        for r in replacements:
            file_contents = file_contents.replace(r, replacements[r])
        with open(path, "w+") as fp:
            fp.write(file_contents)
